#pragma config(Sensor, S1,     HTPB,           sensorI2CCustom9V)
#pragma config(Sensor, S2,     ,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Arduino to Hitechnic Protoboard
// Wiring:
//  Arduino   to     Hitechnic
//    D0                A0
//    D1                A1
//    D9                A2
//    D3                A3
//    D4                A4
//    D5                B0
//    D6                B1
//    D7                B2
//    D8                B3
//    D2 (interupt)     B4 (output)
//////////////////////////////////

#include "drivers/hitechnic-protoboard.h"

int RawReadingToDegrees(int nineBitNum)
{
	float Degrees = 0;
	float NineBitNum = 0;
	float slope = 360.0/512.0;

	NineBitNum = (float)(nineBitNum);
	Degrees=slope*NineBitNum;
	Degrees=Degrees - 180.0;
	return (int)(Degrees);
}

task main()
{
  int AnalogPins = 0;  // analog input
  byte DigitalPins = 0;  // all digital inputs
  int RawReading = 0;

  nxtDisplayCenteredTextLine(0, "HiTechnic");
  nxtDisplayCenteredBigTextLine(1, "Proto");
  nxtDisplayCenteredTextLine(3, "Test 1");
  nxtDisplayCenteredTextLine(5, "Connect HTPB");
  nxtDisplayCenteredTextLine(6, "to S1");

  wait1Msec(2000);

  // Setup all the digital IO ports as outputs (0x10) 010000 pin B4 = output, others are inputs.
  if (!HTPBsetupIO(HTPB, 0x10))
  {
    nxtDisplayTextLine(4, "ERROR!!");
    wait1Msec(2000);
    StopAllTasks();
  }

  while(true)
  {
  	//reset the reading value
    RawReading = 0;

    //clear the NXT
  	eraseDisplay();

  	//get the analog values
		for(int i = 0; i < 5; i++)
		{
			AnalogPins = HTPBreadADC(HTPB, i, 10);

			nxtDisplayTextLine(i, "A0: %d", AnalogPins);

			if (AnalogPins > 512)
			{
				RawReading += (1 << (4 + (4 - i));
			}
		}

		//get the digital values
	  DigitalPins = HTPBreadIO(HTPB, 0x3F);
	  nxtDisplayTextLine(5, "D: 0x%x", DigitalPins);
	  RawReading += (DigitalPins&0x01) << 3;
	  RawReading += (DigitalPins&0x02) << 1;
	  RawReading += (DigitalPins&0x04) >> 1;
	  RawReading += (DigitalPins&0x08) >> 3;

	  nxtDisplayBigTextLine(6, "%d", RawReadingToDegrees(RawReading));

	  //let other threads do shit
	  wait1Msec(50);
	}
}
