#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S2,     HTPB,           sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "./Rotation.c"
#include "../Libraries/Motors.h"

void Move(int SpeedLeft, int SpeedRight)
{
	Motors_SetSpeed(S1, 1, 1, SpeedRight);
	Motors_SetSpeed(S1, 1, 2, SpeedLeft);
}

task main()
{
	int TargetDegree = 90;

	while(true)
	{
		//globals
		bool Connected = Rotation_SensorConnected();
		int Degree = Rotation_Degrees();

		//display debug to NXT
		eraseDisplay();
		nxtDisplayString(1, "Working: %i", Connected);
		nxtDisplayString(2, "Degree: %i", Degree);

		//move
		int Error = abs(Degree - TargetDegree);




		wait1Msec(50);
	}
}
